#
# cmake/reflect/_Headers.cmake is generated by `mulle-sde reflect`. Edits will be lost.
#
if( MULLE_TRACE_INCLUDE)
   MESSAGE( STATUS "# Include \"${CMAKE_CURRENT_LIST_FILE}\"" )
endif()

set( INCLUDE_DIRS
src
src/reflect
)

set( PRIVATE_GENERATED_HEADERS
src/reflect/_MulleZlib-import-private.h
src/reflect/_MulleZlib-include-private.h
)

set( PRIVATE_HEADERS
src/import-private.h
src/include-private.h
)

set( PUBLIC_GENERATED_HEADERS
src/reflect/_MulleZlib-import.h
src/reflect/_MulleZlib-include.h
)

set( PUBLIC_HEADERS
src/MulleZlib.h
src/NSData+MulleZlib.h
src/import.h
src/include.h
)

