#ifndef mulle_zlib_include_private_h__
#define mulle_zlib_include_private_h__

/* This is a central include file to not expose includes to consumers of
   this library. It must not be imported by .h files, but by .c files
   only.
 */

#include "include.h"

/* Include the header file automatically generated by c-sourcetree-update.
   Here the prefix is harmless and serves disambiguation. If you have no
   sourcetree, then you don't need it.
 */

#include "_MulleZlib-include-private.h"

/* You can add some more include statements here */

#if defined(MSDOS) || defined(OS2) || defined(WIN32) || defined(__CYGWIN__)
#  include <fcntl.h>
#  include <io.h>
#  define SET_BINARY_MODE(file) setmode(fileno(file), O_BINARY)
#else
#  define SET_BINARY_MODE(file)
#endif

#endif
