/*
   This file will be regenerated by `mulle-sde update|monitor`.
   Edits will be lost.
   Suppress this file with MULLE_SOURCETREE_TO_C_INCLUDE_FILE NONE|DISABLE.
*/
/*
   This file will be regenerated by `mulle-sde update|monitor`.
   Edits will be lost.
   Suppress this file with MULLE_SOURCETREE_TO_C_INCLUDE_FILE NONE|DISABLE.
*/

#ifndef _mulle_objc_zlib_foundation_include_h__
#define _mulle_objc_zlib_foundation_include_h__

# if defined( __APPLE__)
#  include <zlib.h>   // z
# endif

# if ! defined( __APPLE__)
#  include <zlib.h>   // zlib
# endif

#endif

