/*
   This file will be regenerated by `mulle-sde update|monitor`.
   Edits will be lost.
*/

#ifndef _mulle_objc_zlib_foundation_import_h__
#define _mulle_objc_zlib_foundation_import_h__

/* no headers */

#endif
