/*
   This file will be regenerated by `mulle-sde update|monitor`.
   Edits will be lost.
*/

#ifndef _mulle_objc_zlib_foundation_include_h__
#define _mulle_objc_zlib_foundation_include_h__

# include <MulleObjCStandardFoundation/MulleObjCStandardFoundation.h>   // MulleObjCStandardFoundation

# if defined( __APPLE__)
#  include <z.h>   // z
# endif

# if ! defined( __APPLE__)
#  include <zlib.h>   // zlib
# endif

#endif
