/*
*   This file will be regenerated by `mulle-sde update` and any edits will be
*   lost. Suppress generation of this file with:
*      mulle-sde environment --global \
*         set MULLE_SOURCETREE_TO_C_INCLUDE_FILE DISABLE
*
*   To not generate any header files:
*      mulle-sde environment --global \
*         set MULLE_SOURCETREE_TO_C_RUN DISABLE
*/

#ifndef _mulle_zlib_include_h__
#define _mulle_zlib_include_h__

// How to tweak the following z #include
//    remove:          `mulle-sourcetree mark z no-header`
//    rename:          `mulle-sourcetree mark z set include whatever.h`
//    toggle public:   `mulle-sourcetree mark z [no-]public`
//    toggle optional: `mulle-sourcetree mark z [no-]require`
//    remove for os:   `mulle-sourcetree mark z no-os-<osname>`
# if defined( __APPLE__)
#  include <zlib.h>   // z
# endif

// How to tweak the following zlib #include
//    remove:          `mulle-sourcetree mark zlib no-header`
//    rename:          `mulle-sourcetree mark zlib set include whatever.h`
//    toggle public:   `mulle-sourcetree mark zlib [no-]public`
//    toggle optional: `mulle-sourcetree mark zlib [no-]require`
//    remove for os:   `mulle-sourcetree mark zlib no-os-<osname>`
# if ! defined( __APPLE__)
#  include <zlib.h>   // zlib
# endif

#endif
