/*
*   This file will be regenerated by `mulle-sde update` and any edits will be
*   lost. Suppress generation of this file with:
*      mulle-sde environment --global *         set MULLE_SOURCETREE_TO_C_INCLUDE_FILE DISABLE
*
*   To not generate any header files:
*      mulle-sde environment --global *         set MULLE_SOURCETREE_TO_C_RUN DISABLE
*/

#ifndef _mulle_objc_zlib_foundation_include_h__
#define _mulle_objc_zlib_foundation_include_h__

// remove with `mulle-sourcetree mark z no-header`
// rename with `mulle-sourcetree mark z set include whatever.h`
# if defined( __APPLE__)
#  include <zlib.h>   // z
# endif

// remove with `mulle-sourcetree mark zlib no-header`
// rename with `mulle-sourcetree mark zlib set include whatever.h`
# if ! defined( __APPLE__)
#  include <zlib.h>   // zlib
# endif

#endif
