#
# cmake/_Libraries.cmake is generated by `mulle-sde`. Edits will be lost.
#
if( MULLE_TRACE_INCLUDE)
   message( STATUS "# Include \"${CMAKE_CURRENT_LIST_FILE}\"" )
endif()

# sourcetree: Z;no-all-load,no-cmakeinherit,no-import,only-os-darwin;
if( ${CMAKE_SYSTEM_NAME} MATCHES "Darwin")
   if( NOT Z_LIBRARY)
      find_library( Z_LIBRARY NAMES z)
      message( STATUS "Z_LIBRARY is ${Z_LIBRARY}")
      #
      # the order looks ascending, but due to the way this file is read
      # it ends up being descending, which is what we need
      if( Z_LIBRARY)
         #
         # Add to Z_LIBRARY list.
         # Disable with: `mark no-cmakeadd`
         #
         set( OS_SPECIFIC_LIBRARIES
            ${OS_SPECIFIC_LIBRARIES}
            ${Z_LIBRARY}
            CACHE INTERNAL "need to cache this"
         )
         # intentionally left blank
      else()
         message( FATAL_ERROR "Z_LIBRARY was not found")
      endif()
   endif()
endif()
