#
# cmake/_Sources.cmake is generated by `mulle-sde`. Edits will be lost.
#
if( MULLE_TRACE_INCLUDE)
   MESSAGE( STATUS "# Include \"${CMAKE_CURRENT_LIST_FILE}\"" )
endif()

set( SOURCES
src/MulleObjCZlibFoundation.m
src/NSData+MulleObjCZlibFoundation.m
)

set( STAGE2_SOURCES
src/MulleObjCLoader+MulleObjCZlibFoundation.m
)

set( STANDALONE_SOURCES
src/MulleObjCZlibFoundation-standalone.m
)
